name: CI/CD con Docker

on:
  push:
    branches: [ "main" ]   # se ejecuta cuando haces push a main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write        # necesario para publicar en GHCR

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar metadatos de la imagen Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        # Esto genera tags y labels basados en la rama/commit (ej: :sha, :main)

    - name: Iniciar sesión en GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Construir y publicar la imagen Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
